### ISSUE TITLE
invalid integer range

### ISSUE THREAD

**Issue by dandaman** [ropensci/open-science-with-R#5]
Hi Scott,

I just stumbled over you nice intro 03-internet-databases.md, because I was googling the "invalid interger range error" I keep getting using the  occ_search method of rgbif.

Sorry for sort of hijacking the issue feature for this wiki, but are you also getting this error? Or what does the comment indicate?

As it is - I think its a bit misleading for readers...

I'm trying to get occurence data for ~1400 species. Already tried it as a whole or in chunks of 50 and 100.

Best,
Daniel

**Comment by sckott** [comment]
hi @dandaman - Can we move this discussion to the `rgbif` repository? can you repost this question there. https://github.com/ropensci/rgbif/issues  In your question, can you give what version of `rgbif` you're using, and an example call that gives the error

**Comment by dandaman** [comment]
Of course. Doing it right now.
